from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
import joblib
import pandas as pd
from pathlib import Path
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer


def load_processed_dataset(project_root):
    """Load the CSV generated by data_preprocessing.py"""
    data_path = project_root / "data" / "processed" / "cleaned_malaysia_house_prices.csv"

    print("Loading cleaned dataset...")
    try:
        return pd.read_csv(data_path)
    except FileNotFoundError:
        raise FileNotFoundError(f"Raw dataset not found at {data_path}")


def split_dataset(
        df, categorical_features, numerical_features,
        type_features, target="Median_Price"
):
    X = df[categorical_features + numerical_features + type_features]
    y = df[target]

    state_counts = df["State"].value_counts()
    rare_states = state_counts[state_counts < 2].index

    if len(rare_states) == 0:
        return train_test_split(X, y, test_size=0.2, random_state=42, stratify=df["State"])
    else:
        return train_test_split(X, y, test_size=0.2, random_state=42)


def remove_outliers_train_only(
        X_train, y_train, numerical_columns
):
    """Safely removes outliers ONLY from the training set using IQR."""
    train_data = X_train.copy()
    train_data['TARGET_TEMP'] = y_train

    # Filter outliers for target variable
    Q1_y = train_data['TARGET_TEMP'].quantile(0.25)
    Q3_y = train_data['TARGET_TEMP'].quantile(0.75)
    IQR_y = Q3_y - Q1_y
    train_data = train_data[(train_data['TARGET_TEMP'] >= Q1_y - 1.5 * IQR_y) &
                            (train_data['TARGET_TEMP'] <= Q3_y + 1.5 * IQR_y)]

    # Filter outliers for numerical features (like Transactions)
    for col in numerical_columns:
        if col in train_data.columns:
            Q1 = train_data[col].quantile(0.25)
            Q3 = train_data[col].quantile(0.75)
            IQR = Q3 - Q1
            train_data = train_data[(train_data[col] >= Q1 - 1.5 * IQR) &
                                    (train_data[col] <= Q3 + 1.5 * IQR)]

    y_train_clean = train_data['TARGET_TEMP']
    X_train_clean = train_data.drop(columns=['TARGET_TEMP'])

    print(f"Removed {len(y_train) - len(y_train_clean)} outliers from training set.")
    return X_train_clean, y_train_clean


def build_preprocessor(
        numerical_features, categorical_features, type_features
):
    numeric_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])

    categorical_transformer = Pipeline([
        ("imputer", SimpleImputer(strategy="constant", fill_value="Missing")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", min_frequency=5))
    ])

    return ColumnTransformer([
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features),
        ("type", "passthrough", type_features),
    ])


def print_metrics(
        model_name, y_true,y_pred
):
    # 1. Calculate Real-World Metrics
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    # 2. Calculate Log-Transformed Metrics (The "0.something" illusion)
    # We apply the natural logarithm to both actual and predicted prices
    y_true_log = np.log1p(y_true)
    y_pred_log = np.log1p(y_pred)

    log_mae = mean_absolute_error(y_true_log, y_pred_log)
    log_rmse = np.sqrt(mean_squared_error(y_true_log, y_pred_log))

    # Note: R-squared usually remains identical or very similar because it measures
    # variance explained, which scales proportionally.
    log_r2 = r2_score(y_true_log, y_pred_log)

    # 3. Display the comparison cleanly
    print("-" * 45)
    print(f"{model_name} Performance")
    print("-" * 45)
    print("REAL-WORLD METRICS (Actual Ringgit):")
    print(f"MAE: RM {mae:,.2f}")
    print(f"RMSE: RM {rmse:,.2f}")
    print(f"R² : {r2:.4f}")
    print("-" * 45)
    print("LOG-TRANSFORMED METRICS:")
    print(f"Log MAE: {log_mae:.4f}")
    print(f"Log RMSE: {log_rmse:.4f}")
    print(f"Log R²: {log_r2:.4f}")
    print("-" * 45)

    return mae, rmse, r2


def save_model(
        model, output_path
):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, output_path)

    print(f"Model saved to {output_path}")


def load_model(
        path
):
    return joblib.load(path)